# Generated by Django 5.2 on 2026-04-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_create_territoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='actiu',
        ),
    ]
