# Generated by Django 5.2 on 2026-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_remove_artista_actiu"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="deezer_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="deezer_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="deezer_no_trobat",
            field=models.BooleanField(
                default=False,
                help_text="True if Deezer search failed ISRC validation — skip in future runs.",
            ),
        ),
        migrations.AddField(
            model_name="canco",
            name="deezer_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
