# Generated by Django 5.2 on 2026-04-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_add_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="deezer_nb_album",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="deezer_nb_fan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="deezer_nom",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="artista",
            name="deezer_nom_similitud",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistorialRevisio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canco_deezer_id", models.BigIntegerField(blank=True, null=True)),
                ("canco_spotify_id", models.CharField(blank=True, max_length=50)),
                ("canco_isrc", models.CharField(blank=True, max_length=20)),
                ("canco_nom", models.CharField(max_length=500)),
                ("artista_nom", models.CharField(max_length=255)),
                ("artista_territori", models.CharField(blank=True, max_length=10)),
                ("album_nom", models.CharField(blank=True, max_length=500)),
                ("data_llancament", models.DateField(blank=True, null=True)),
                ("isrc_prefix", models.CharField(blank=True, max_length=5)),
                ("artista_deezer_id", models.BigIntegerField(blank=True, null=True)),
                ("artista_deezer_nb_fan", models.IntegerField(blank=True, null=True)),
                ("artista_deezer_nb_album", models.IntegerField(blank=True, null=True)),
                ("artista_nom_deezer", models.CharField(blank=True, max_length=255)),
                ("artista_nom_similitud", models.FloatField(blank=True, null=True)),
                (
                    "decisio",
                    models.CharField(
                        choices=[("aprovada", "Aprovada"), ("rebutjada", "Rebutjada")],
                        max_length=20,
                    ),
                ),
                (
                    "motiu",
                    models.CharField(
                        choices=[
                            ("ok", "En català i correcte"),
                            ("no_catala", "La cançó no és en català"),
                            (
                                "artista_incorrecte",
                                "El perfil Deezer no és el nostre artista",
                            ),
                            (
                                "album_incorrecte",
                                "L'àlbum sencer no pertany al nostre artista",
                            ),
                            ("no_musica", "No és música (podcast, audiollibre...)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial de revisió",
                "verbose_name_plural": "Historial de revisions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["decisio", "motiu"],
                        name="music_histo_decisio_7d591c_idx",
                    ),
                    models.Index(
                        fields=["canco_isrc"], name="music_histo_canco_i_d3c53c_idx"
                    ),
                    models.Index(
                        fields=["artista_deezer_id"],
                        name="music_histo_artista_9faefd_idx",
                    ),
                ],
            },
        ),
    ]
