# Generated by Django 5.2 on 2026-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_artista_deezer_nb_album_artista_deezer_nb_fan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="preview_url",
            field=models.URLField(blank=True),
        ),
    ]
