# Generated by Django 5.2 on 2026-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_canco_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='canco',
            name='ml_classe',
            field=models.CharField(blank=True, db_index=True, max_length=1),
        ),
        migrations.AddField(
            model_name='canco',
            name='ml_confianca',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
