# Generated by Django 5.2 on 2026-04-15
# Split migration: add slug as CharField, populate, then convert to SlugField(unique).

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate unique slugs for all existing artists."""
    Artista = apps.get_model("music", "Artista")
    seen: dict[str, int] = {}
    for artista in Artista.objects.all().order_by("id"):
        base = slugify(artista.nom) or "artista"
        if base not in seen:
            seen[base] = 1
            artista.slug = base
        else:
            seen[base] += 1
            artista.slug = f"{base}-{seen[base]}"
        artista.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0017_add_ml_fields_to_historialrevisio"),
    ]

    operations = [
        # Step 1: add as plain CharField (no indexes)
        migrations.AddField(
            model_name="artista",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=280),
            preserve_default=False,
        ),
        # Step 2: populate all slugs
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: convert to SlugField with unique constraint
        migrations.AlterField(
            model_name="artista",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
