# Generated by Django 5.2 on 2026-04-15

from django.db import migrations, models
from django.utils.text import slugify


def populate_album_slugs(apps, schema_editor):
    """Populate slug for all existing albums."""
    Album = apps.get_model("music", "Album")
    used_slugs = set()
    for album in Album.objects.all().order_by("id"):
        base = slugify(album.nom) or "album"
        # Truncate base to avoid exceeding max_length with suffix
        base = base[:500]
        slug = base
        n = 1
        while slug in used_slugs:
            n += 1
            slug = f"{base}-{n}"
        used_slugs.add(slug)
        album.slug = slug
        album.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_add_artista_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArtistaPendent",
        ),
        # Step 1: add slug field, nullable, no unique (allows empty default)
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.CharField(max_length=550, default="", blank=True),
            preserve_default=False,
        ),
        # Step 2: populate all slugs
        migrations.RunPython(populate_album_slugs, migrations.RunPython.noop),
        # Step 3: convert to SlugField with unique constraint
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=550, unique=True),
        ),
    ]
