# Generated by Django 5.2 on 2026-04-16 10:59

from django.db import migrations


def copy_deezer_ids(apps, schema_editor):
    """Copy Artista.deezer_id values to ArtistaDeezer model."""
    Artista = apps.get_model("music", "Artista")
    ArtistaDeezer = apps.get_model("music", "ArtistaDeezer")
    rows = []
    for artista in Artista.objects.filter(deezer_id__isnull=False).iterator():
        if not ArtistaDeezer.objects.filter(deezer_id=artista.deezer_id).exists():
            rows.append(
                ArtistaDeezer(
                    artista=artista,
                    deezer_id=artista.deezer_id,
                    principal=True,
                )
            )
    ArtistaDeezer.objects.bulk_create(rows, batch_size=500)


def reverse(apps, schema_editor):
    """No-op reverse — old field still has the data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0020_add_social_genre_deezer_multi"),
    ]

    operations = [
        migrations.RunPython(copy_deezer_ids, reverse),
    ]
