# Generated by Django 5.2 on 2026-04-16

from django.db import migrations
from django.db.models import Q


def unapprove_without_location(apps, schema_editor):
    """Set aprovat=False for artists missing localitat or comarca."""
    Artista = apps.get_model("music", "Artista")
    count = Artista.objects.filter(aprovat=True).filter(
        Q(localitat="") | Q(localitat__isnull=True) |
        Q(comarca="") | Q(comarca__isnull=True)
    ).update(aprovat=False)
    if count:
        print(f"  Unapproved {count} artists without localitat/comarca.")


def titlecase_cancons(apps, schema_editor):
    """Apply TitleCase to all song titles."""
    Canco = apps.get_model("music", "Canco")
    updated = 0
    for canco in Canco.objects.all().iterator():
        new_nom = canco.nom.title()
        if new_nom != canco.nom:
            Canco.objects.filter(pk=canco.pk).update(nom=new_nom)
            updated += 1
    if updated:
        print(f"  TitleCased {updated} song titles.")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_copy_deezer_ids_to_m2m'),
    ]

    operations = [
        migrations.RunPython(unapprove_without_location, noop),
        migrations.RunPython(titlecase_cancons, noop),
    ]
