# Generated by Django 5.2 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0023_catalan_titlecase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="territoris",
            field=models.ManyToManyField(
                blank=True,
                help_text="Auto-synced from ArtistaLocalitat. Do not edit directly.",
                related_name="artistes",
                to="music.territori",
            ),
        ),
        migrations.CreateModel(
            name="Municipi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("comarca", models.CharField(max_length=255)),
                (
                    "territori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipis",
                        to="music.territori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipi",
                "verbose_name_plural": "Municipis",
                "ordering": ["nom"],
                "unique_together": {("nom", "comarca")},
            },
        ),
        migrations.CreateModel(
            name="ArtistaLocalitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localitat_manual",
                    models.CharField(
                        blank=True,
                        help_text="Free text for non-PPCC locations or display override.",
                        max_length=255,
                    ),
                ),
                (
                    "descripcio",
                    models.CharField(
                        blank=True,
                        help_text="Optional qualifier, e.g. 'nascut a' or 'resident a'.",
                        max_length=255,
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localitats",
                        to="music.artista",
                    ),
                ),
                (
                    "municipi",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for non-PPCC artists (Altres).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artistes_localitat",
                        to="music.municipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localitat d'artista",
                "verbose_name_plural": "Localitats d'artista",
            },
        ),
    ]
