# Generated by Django 5.2 on 2026-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_populate_municipis_and_localitats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cancons_obtingudes',
            field=models.BooleanField(db_index=True, default=False, help_text='True when tracks have been fetched from Deezer.'),
        ),
        migrations.AlterField(
            model_name='album',
            name='descartat',
            field=models.BooleanField(db_index=True, default=False, help_text='True if all tracks were rejected. Skipped by obtenir_novetats.'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='aprovat',
            field=models.BooleanField(db_index=True, default=True, help_text='False = pending human review in staff panel.'),
        ),
        migrations.AlterField(
            model_name='canco',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='canco',
            name='data_llancament',
            field=models.DateField(blank=True, db_index=True, help_text='Tracks older than 12 months are excluded from ingestion.', null=True),
        ),
        migrations.AlterField(
            model_name='canco',
            name='verificada',
            field=models.BooleanField(db_index=True, default=False, help_text='False = pending admin review. Only verified tracks enter the ranking.'),
        ),
    ]
