# Generated by Django 5.2 on 2026-04-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0026_add_indexes_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("canco_aprovar", "Cançó: aprovar"),
                            ("canco_rebutjar", "Cançó: rebutjar"),
                            ("canco_rebutjar_album", "Cançó: rebutjar àlbum sencer"),
                            ("canco_edit", "Cançó: edició"),
                            ("artista_aprovar", "Artista: aprovar"),
                            ("artista_rebutjar", "Artista: rebutjar"),
                            (
                                "artista_marcar_sense_deezer",
                                "Artista: marcar sense Deezer",
                            ),
                            ("artista_fusionar", "Artista: fusionar"),
                            ("artista_edit", "Artista: edició"),
                            ("pendent_aprovar", "Pendent: aprovar"),
                            ("pendent_descartar", "Pendent: descartar"),
                            ("album_edit", "Àlbum: edició"),
                            ("album_descartar", "Àlbum: descartar"),
                            ("proposta_aprovar", "Proposta: aprovar"),
                            ("proposta_rebutjar", "Proposta: rebutjar"),
                            ("sollicitud_aprovar", "Sol·licitud: aprovar"),
                            ("sollicitud_rebutjar", "Sol·licitud: rebutjar"),
                            ("config_update", "Configuració global: actualitzada"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Canco", "Artista", "Album", "Proposta", "Config".',
                        max_length=30,
                    ),
                ),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identifier of the target at action time.",
                        max_length=500,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who performed the action. NULL if actor was deleted — the action itself is still in the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada d'auditoria staff",
                "verbose_name_plural": "Auditoria staff",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="music_staff_created_645b57_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="music_staff_action_b23930_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="music_staff_actor_i_52f0dc_idx",
                    ),
                ],
            },
        ),
    ]
