# Generated by Django 5.2 on 2026-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_add_staff_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauditlog',
            name='action',
            field=models.CharField(choices=[('canco_aprovar', 'Cançó: aprovar'), ('canco_rebutjar', 'Cançó: rebutjar'), ('canco_rebutjar_album', 'Cançó: rebutjar àlbum sencer'), ('canco_edit', 'Cançó: edició'), ('artista_aprovar', 'Artista: aprovar'), ('artista_rebutjar', 'Artista: rebutjar'), ('artista_marcar_sense_deezer', 'Artista: marcar sense Deezer'), ('artista_fusionar', 'Artista: fusionar'), ('artista_edit', 'Artista: edició'), ('pendent_aprovar', 'Pendent: aprovar'), ('pendent_descartar', 'Pendent: descartar'), ('album_edit', 'Àlbum: edició'), ('album_descartar', 'Àlbum: descartar'), ('proposta_aprovar', 'Proposta: aprovar'), ('proposta_rebutjar', 'Proposta: rebutjar'), ('sollicitud_aprovar', 'Sol·licitud: aprovar'), ('sollicitud_rebutjar', 'Sol·licitud: rebutjar'), ('config_update', 'Configuració global: actualitzada'), ('usuari_desactivar', 'Usuari: desactivar'), ('usuari_reactivar', 'Usuari: reactivar'), ('usuari_reset_2fa', 'Usuari: reset 2FA')], max_length=40),
        ),
    ]
