# Generated by Django 5.2 on 2026-04-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_lastfm_drift_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='deezer_id',
        ),
    ]
