# Generated by Django 5.2 on 2026-04-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_r10_remove_artista_deezer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='comarca',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='localitat',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='provincia',
        ),
    ]
