# Generated by Django 5.2 on 2026-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0031_r11_remove_legacy_location_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="canco",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isrc", ""), _negated=True),
                fields=("isrc",),
                name="canco_isrc_unique_when_set",
            ),
        ),
    ]
