# Generated by Django 5.2 on 2026-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_d1_canco_isrc_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialrevisio',
            index=models.Index(fields=['artista_nom', 'decisio'], name='music_histo_artista_0f59ce_idx'),
        ),
        migrations.AddIndex(
            model_name='historialrevisio',
            index=models.Index(fields=['isrc_prefix', 'decisio'], name='music_histo_isrc_pr_27c1bb_idx'),
        ),
    ]
