# Generated by Django 5.2 on 2026-04-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_d5_cleanup_self_collabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='lastfm_mbid',
        ),
        migrations.RemoveField(
            model_name='canco',
            name='lastfm_mbid',
        ),
        migrations.RemoveField(
            model_name='canco',
            name='lastfm_verificat',
        ),
    ]
