# Generated by Django 5.2 on 2026-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0035_d2_drop_dead_lastfm_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="canco",
            index=models.Index(
                fields=["verificada", "artista"], name="music_canco_verific_45512c_idx"
            ),
        ),
    ]
