# Generated by Django 5.2 on 2026-04-18 12:49

from django.db import migrations, models


def backfill_lastfm_te_scrobbles(apps, schema_editor):
    """Set lastfm_te_scrobbles=True for any Artista whose tracks have
    at least one non-error SenyalDiari row with playcount > 0."""
    Artista = apps.get_model("music", "Artista")
    SenyalDiari = apps.get_model("ranking", "SenyalDiari")

    active_artist_ids = set(
        SenyalDiari.objects.filter(error=False, lastfm_playcount__gt=0)
        .values_list("canco__artista_id", flat=True)
        .distinct()
    )
    if active_artist_ids:
        Artista.objects.filter(pk__in=active_artist_ids).update(
            lastfm_te_scrobbles=True
        )


def noop(apps, schema_editor):
    # Reversing the field drop is the migration's own AddField; no data
    # work to reverse here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0036_d6_composite_indexes"),
        # Data backfill reads SenyalDiari — need the ranking app state.
        ("ranking", "0009_d6_composite_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="lastfm_te_scrobbles",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True iff Last.fm returned playcount>0 for at "
                "least one track by this artist. Maintained by "
                "obtenir_senyal.",
            ),
        ),
        migrations.RunPython(backfill_lastfm_te_scrobbles, noop),
    ]
