# Generated by Django 5.2 on 2026-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0037_add_lastfm_te_scrobbles"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="silero_processat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="canco",
            name="silero_veu_probabilitat",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
