# Generated by Django 5.2 on 2026-04-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0038_silero_vad_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canco",
            name="silero_processat_at",
        ),
        migrations.RemoveField(
            model_name="canco",
            name="silero_veu_probabilitat",
        ),
    ]
