# Generated by Django 5.2 on 2026-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0039_revert_silero_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="whisper_lang",
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name="canco",
            name="whisper_p",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="canco",
            name="whisper_processat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
