# Generated by Django 5.2 on 2026-04-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0040_whisper_lid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="whisper_all_probs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
