# Generated by Django 5.2 on 2026-04-19 08:56
#
# Introduces `pendent_review` as the canonical "in staff triage queue"
# flag, separate from `auto_descobert` (now immutable discovery
# provenance). Includes a data migration that:
#   - flips pendent_review=True for everyone currently sitting in the
#     old pendents query (aprovat=False AND auto_descobert=True);
#   - cleans up 40 legacy-migration orphans (font_descoberta='legacy',
#     zero cançons, aprovat=False, auto_descobert=False);
#   - surfaces the 2 stranded artists that have verified tracks but no
#     provenance flag by putting them into pendents too.
# See the Sessió 17 audit for the full list of issues this addresses.

from django.db import migrations, models


def forwards(apps, schema_editor):
    Artista = apps.get_model("music", "Artista")
    Canco = apps.get_model("music", "Canco")

    # 1. Everyone in the old pendents query → pendent_review=True.
    Artista.objects.filter(aprovat=False, auto_descobert=True).update(
        pendent_review=True,
    )

    # 2. The 42-artist limbo: aprovat=False, auto_descobert=False.
    #    Split by presence of verified tracks:
    #    - with verified tracks: surface them (send to pendents)
    #    - legacy orphans with zero tracks: delete
    limbo = Artista.objects.filter(aprovat=False, auto_descobert=False)

    # 2a) Surface the ones that ARE in the catalogue via verified tracks.
    with_verified_pks = set(
        Canco.objects.filter(verificada=True, artista__in=limbo).values_list(
            "artista_id", flat=True
        )
    )
    if with_verified_pks:
        Artista.objects.filter(pk__in=with_verified_pks).update(
            pendent_review=True,
        )

    # 2b) Delete legacy migration orphans with zero cançons.
    limbo.exclude(pk__in=with_verified_pks).filter(
        cancons__isnull=True,
        font_descoberta="legacy",
    ).delete()

    # 3. The 29 `aprovat=True, auto_descobert=True` anomalies are NOT
    #    rewritten: auto_descobert is the immutable provenance flag
    #    from now on, and we don't want to destroy that record. The new
    #    CheckConstraint only forbids (aprovat=True, pendent_review=True),
    #    which the new default (pendent_review=False) already satisfies
    #    for every row, so no further cleanup is required here.


def backwards(apps, schema_editor):
    # The data migration is idempotent on its own, but we don't try to
    # re-create the deleted orphans — they were migration dust with no
    # associated data.
    pass


class Migration(migrations.Migration):
    # Non-atomic: we mix DDL (AddField, AddIndex, AddConstraint) with a
    # RunPython that executes SELECT/UPDATE/DELETE against the very
    # column we just created. Postgres refuses to build an index when
    # there are pending row-level trigger events from the same tx, so
    # each step gets its own transaction.
    atomic = False

    dependencies = [
        ("music", "0041_whisper_all_probs"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="pendent_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = appears in /staff/artistes/pendents/ for review.",
            ),
        ),
        migrations.AlterField(
            model_name="artista",
            name="auto_descobert",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True if the artist was auto-discovered (feat. "
                    "resolution, Viasona ingest, etc.). Historical record "
                    "of how the artist got into the system — NOT to be "
                    "used as an 'in pendents queue' flag. Use "
                    "`pendent_review` for that."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="artista",
            name="font_descoberta",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Source: 'viasona', 'collaborador', 'deezer_contributor', "
                    "'manual', 'legacy'."
                ),
                max_length=50,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AddIndex(
            model_name="artista",
            index=models.Index(
                fields=["pendent_review", "aprovat"],
                name="artista_pendent_review_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="artista",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aprovat", True), ("pendent_review", True), _negated=True
                ),
                name="artista_no_aprovat_pendent_review",
            ),
        ),
    ]
