# Generated by Django 5.2 on 2026-04-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0043_add_artista_crear_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artista",
            name="deezer_no_trobat",
        ),
    ]
