# Generated by Django 5.2 on 2026-04-20 10:01
#
# Adds a globally-unique slug to every Canco + backfills from
# `<artista-slug>-<canco-slug>` with a numeric suffix on collision.
# Non-atomic because we mix DDL (add field + unique index) with a
# RunPython that writes a value for every row before the UNIQUE
# constraint can be enforced.

from django.db import migrations, models
from django.utils.text import slugify


def forwards(apps, schema_editor):
    Canco = apps.get_model("music", "Canco")
    # We don't have the model's save() override here, so compute the
    # slug exactly the same way (mirror of Canco.save).
    used: set[str] = set()
    # Iterate in a deterministic order so two runs produce the same slugs.
    for canco in (
        Canco.objects.all()
        .select_related("artista")
        .order_by("pk")
        .iterator(chunk_size=500)
    ):
        artist_bit = slugify(canco.artista.nom) if canco.artista_id else ""
        track_bit = slugify(canco.nom) or f"canco-{canco.pk}"
        base = f"{artist_bit}-{track_bit}".strip("-") if artist_bit else track_bit
        base = base[:550]
        slug = base
        n = 1
        while slug in used:
            n += 1
            slug = f"{base}-{n}"
        used.add(slug)
        canco.slug = slug
        canco.save(update_fields=["slug"])


def backwards(apps, schema_editor):
    # No-op — the column gets dropped by the reverse of AddField.
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("music", "0044_drop_deezer_no_trobat"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="slug",
            # First pass: add as nullable-via-blank, not yet unique,
            # so RunPython can fill every row.
            field=models.SlugField(blank=True, max_length=560),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="canco",
            name="slug",
            field=models.SlugField(blank=True, max_length=560, unique=True),
        ),
    ]
