# Generated by Django 5.2 on 2026-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0045_canco_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyAuth",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("refresh_token", models.TextField()),
                ("scope", models.CharField(blank=True, max_length=500)),
                ("spotify_user_id", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Autorització Spotify",
                "verbose_name_plural": "Autoritzacions Spotify",
            },
        ),
        migrations.CreateModel(
            name="SpotifyPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codi", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("top", "Top provisional"), ("novetats", "Novetats")],
                        max_length=20,
                    ),
                ),
                ("territori", models.CharField(blank=True, max_length=10)),
                ("spotify_playlist_id", models.CharField(blank=True, max_length=100)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_ok", models.BooleanField(default=True)),
                ("last_sync_msg", models.TextField(blank=True)),
                ("last_n_tracks", models.IntegerField(default=0)),
                ("last_n_matched", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Playlist Spotify",
                "verbose_name_plural": "Playlists Spotify",
                "ordering": ["codi"],
            },
        ),
    ]
