# Generated by Django 5.2 on 2026-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0046_spotifyauth_spotifyplaylist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="mb_release_group_id",
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name="album",
            name="mb_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="album",
            name="mb_type_secondary",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="album",
            name="mbrainz_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_area",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_area_hierarchy",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_begin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_disambiguation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_discography_cache",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_end_date",
            field=models.DateField(
                blank=True,
                help_text="Dissolution / cessation date. New releases past this date are almost certainly a different artist with the same name.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_last_sync",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_sort_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="artista",
            name="musicbrainz_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="MBID (UUID) — the authoritative ID for Crim-style collisions.",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="canco",
            name="mb_lyrics_language",
            field=models.CharField(
                blank=True,
                help_text="Work.language from MusicBrainz ('cat' = strong Catalan signal).",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="canco",
            name="mb_recording_id",
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name="canco",
            name="mb_work_id",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="canco",
            name="mbrainz_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
