# Generated by Django 5.2 on 2026-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyArtista',
            fields=[
                ('id_spotify', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('nom_spotify', models.TextField(null=True)),
                ('territori', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('catala', models.BooleanField(db_column='català', null=True)),
                ('localitat', models.CharField(max_length=255, null=True)),
                ('comarca', models.CharField(max_length=255, null=True)),
                ('id_viasona', models.TextField(null=True)),
                ('font_dades', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'artistes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyCanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_canco', models.CharField(max_length=50)),
                ('territori', models.CharField(max_length=50)),
                ('titol', models.TextField(null=True)),
                ('artista_basat', models.TextField(null=True)),
                ('album_id', models.CharField(max_length=50, null=True)),
                ('album_titol', models.TextField(null=True)),
                ('album_data', models.DateField(null=True)),
                ('album_caratula_url', models.TextField(null=True)),
                ('exclosa', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cançons',
                'managed': False,
            },
        ),
    ]
