# Generated by Django 5.2.5 on 2025-08-25 22:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsArtista",
            fields=[
                (
                    "id_spotify",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Spotify",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "nom_spotify",
                    models.TextField(blank=True, null=True, verbose_name="Nom Spotify"),
                ),
                (
                    "generes",
                    models.TextField(blank=True, null=True, verbose_name="Gèneres"),
                ),
                (
                    "territori",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Territori"
                    ),
                ),
                (
                    "comarca",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Comarca"
                    ),
                ),
                (
                    "localitat",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Localitat"
                    ),
                ),
                (
                    "dones",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0%", "0%"),
                            ("<50%", "<50%"),
                            (">50%", ">50%"),
                            ("100%", "100%"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Dones",
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Agència"
                    ),
                ),
                ("web", models.TextField(blank=True, null=True, verbose_name="Web")),
                (
                    "viquipedia",
                    models.TextField(blank=True, null=True, verbose_name="Viquipèdia"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "youtube",
                    models.TextField(blank=True, null=True, verbose_name="YouTube"),
                ),
                (
                    "tiktok",
                    models.TextField(blank=True, null=True, verbose_name="TikTok"),
                ),
                (
                    "soundcloud",
                    models.TextField(blank=True, null=True, verbose_name="SoundCloud"),
                ),
                (
                    "bandcamp",
                    models.TextField(blank=True, null=True, verbose_name="Bandcamp"),
                ),
                (
                    "deezer",
                    models.TextField(blank=True, null=True, verbose_name="Deezer"),
                ),
                (
                    "bluesky",
                    models.TextField(blank=True, null=True, verbose_name="Bluesky"),
                ),
                (
                    "myspace",
                    models.TextField(blank=True, null=True, verbose_name="MySpace"),
                ),
                (
                    "email",
                    models.TextField(blank=True, null=True, verbose_name="Email"),
                ),
                (
                    "telefon",
                    models.TextField(blank=True, null=True, verbose_name="Telèfon"),
                ),
                (
                    "id_viasona",
                    models.TextField(blank=True, null=True, verbose_name="ID Viasona"),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "followers",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Followers"
                    ),
                ),
                (
                    "popularitat",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Popularitat"
                    ),
                ),
                (
                    "imatge_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Imatge (URL)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualitzat"),
                ),
            ],
            options={
                "verbose_name": "Artista",
                "verbose_name_plural": "Artistes",
                "db_table": "cms_artistes",
                "ordering": ("nom",),
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Cos"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro",
            field=models.CharField(blank=True, max_length=255, verbose_name="Subtítol"),
        ),
    ]
