# Generated by Django 5.2.5 on 2025-08-26 17:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_cmsartista_homepage_body_homepage_intro"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Títol del lloc"
                    ),
                ),
                (
                    "subheader",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítol capçalera"
                    ),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                ("tiktok", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "footer_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Text de peu de pàgina"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
