# Generated by Django 5.2.5 on 2025-08-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_globalsettings"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBrandingSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom del lloc"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítol"
                    ),
                ),
                (
                    "show_search",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar cercador al header"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "web_url",
                    models.URLField(blank=True, verbose_name="Enllaç principal"),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="GlobalSettings",
        ),
    ]
