# Generated by Django 5.2.5 on 2025-08-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_sitebrandingsettings_delete_globalsettings"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DissenyDelWeb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom del Web"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=255, verbose_name="Lema"),
                ),
                (
                    "show_search",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar cercador al header"
                    ),
                ),
                (
                    "header_bg",
                    models.CharField(
                        default="#ffffff",
                        max_length=7,
                        verbose_name="Color de fons del header",
                    ),
                ),
                (
                    "header_text_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color del text del header",
                    ),
                ),
                (
                    "header_height",
                    models.PositiveSmallIntegerField(
                        default=48, verbose_name="Alçada del header (px)"
                    ),
                ),
                (
                    "show_subheader",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar subheader amb seccions"
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        default="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-se\
rif",
                        max_length=200,
                        verbose_name="Tipografia base",
                    ),
                ),
                (
                    "body_text_color",
                    models.CharField(
                        default="#111111", max_length=7, verbose_name="Color del text"
                    ),
                ),
                (
                    "link_color",
                    models.CharField(
                        default="#0066cc",
                        max_length=7,
                        verbose_name="Color dels enllaços",
                    ),
                ),
                (
                    "footer_bg",
                    models.CharField(
                        default="#f7f7f7",
                        max_length=7,
                        verbose_name="Color de fons del footer",
                    ),
                ),
                (
                    "footer_text_color",
                    models.CharField(
                        default="#222222",
                        max_length=7,
                        verbose_name="Color del text del footer",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logotip",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disseny del web",
                "verbose_name_plural": "Disseny del web",
            },
        ),
        migrations.DeleteModel(
            name="SiteBrandingSettings",
        ),
    ]
