# Generated by Django 5.2.5 on 2025-08-28 18:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_dissenydelweb_delete_sitebrandingsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="intro",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 2), ("albums", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol", "max_length": 120},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Text curt baix del títol",
                            "label": "Subtítol",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Últims llançaments", "label": "Títol de secció"},
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "label": "Quants àlbums",
                            "max_value": 24,
                            "min_value": 1,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Veure tot",
                            "label": "Text enllaç 'Veure tot'",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Opcional",
                            "label": "URL 'Veure tot'",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 3),
                                ("limit", 4),
                                ("view_all_text", 5),
                                ("view_all_url", 6),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.DeleteModel(
            name="DissenyDelWeb",
        ),
    ]
