# Generated by Django 5.2.5 on 2025-08-29 20:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 2),
                    ("sql_carousel", 14),
                    ("short_text", 15),
                    ("long_text", 16),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol", "max_length": 120},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Text curt baix del títol",
                            "label": "Subtítol",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol de secció", "required": True},
                    ),
                    4: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.SQLTable",),
                        {"label": "Taula (Snippet)"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex: cover_url / imatge_url",
                            "label": "Camp imatge (URL)",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex: album_name / nom",
                            "label": "Camp títol",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Camp subtítol (opcional)", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Si es deixa buit, no s'aplica ORDER BY",
                            "label": "Camp d’ordenació",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("ASC", "Ascendent"), ("DESC", "Descendent")],
                            "label": "Direcció",
                        },
                    ),
                    10: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "label": "Número d’elements",
                            "max_value": 100,
                            "min_value": 1,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Camp filtre (opcional)", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "S'aplica com a = %s",
                            "label": "Valor filtre (opcional)",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "label": "Filtre visible al client (no re-carrega)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 3),
                                ("table", 4),
                                ("image_field", 5),
                                ("title_field", 6),
                                ("subtitle_field", 7),
                                ("order_field", 8),
                                ("order_direction", 9),
                                ("limit", 10),
                                ("filter_field", 11),
                                ("filter_value", 12),
                                ("filter_visible", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {}),
                    16: ("wagtail.blocks.TextBlock", (), {}),
                },
            ),
        ),
    ]
