# Generated by Django 5.2.5 on 2025-08-30 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_homepage_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("artist", "Artista"),
                            ("representant", "Representant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendent"),
                            ("approved", "Aprovat"),
                            ("denied", "Denegat"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Informació addicional (opcional)"
                    ),
                ),
                (
                    "requested_artist_id",
                    models.CharField(
                        blank=True,
                        help_text="id_spotify de l'artista a gestionar (opcional)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user", "status"),
                        name="unique_pending_request_per_user",
                    )
                ],
            },
        ),
    ]
