# Generated by Django 5.2.5 on 2025-08-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_pendingartist_userartistpermission"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, help_text="HEX principal, ex: #0047FF", max_length=7
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="Color text general, ex: #111111",
                        max_length=7,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Color enllaços, ex: #0047FF",
                        max_length=7,
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        help_text="Color fons pàgina, ex: #FFFFFF",
                        max_length=7,
                    ),
                ),
                (
                    "header_bg",
                    models.CharField(
                        blank=True, help_text="Fons header, ex: #FFFFFF", max_length=7
                    ),
                ),
                (
                    "header_text",
                    models.CharField(
                        blank=True, help_text="Text header, ex: #111111", max_length=7
                    ),
                ),
                (
                    "header_height",
                    models.PositiveIntegerField(
                        default=96, help_text="Alçària header en px"
                    ),
                ),
                (
                    "footer_bg",
                    models.CharField(
                        blank=True, help_text="Fons footer, ex: #F7F7F7", max_length=7
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, help_text="Text footer, ex: #222222", max_length=7
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        blank=True,
                        help_text="Stack de font CSS, ex: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, \
sans-serif",
                        max_length=255,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True, help_text="Nom curt del lloc", max_length=120
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo principal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuració de marca",
            },
        ),
    ]
