# Generated by Django 5.2.5 on 2025-09-01 19:28

import django.contrib.postgres.fields
import django.db.models.deletion
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_registrepage_alter_pendingartist_id_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsAlbum",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("album_type", models.TextField()),
                ("release_date", models.TextField()),
                ("image_url", models.TextField(blank=True, null=True)),
                (
                    "artist_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "artist_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("artist_names_str", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Àlbum",
                "verbose_name_plural": "Àlbums",
                "db_table": "cms_albums",
                "ordering": ("release_date", "name"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CmsSong",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("isrc", models.TextField(blank=True, null=True)),
                (
                    "artist_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "artist_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("artist_names_str", models.TextField(blank=True, null=True)),
                ("album_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Cançó",
                "verbose_name_plural": "Cançons",
                "db_table": "cms_songs",
                "ordering": ("-popularity", "name"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MusicIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.AlterModelTable(
            name="cmsartista",
            table="cms_artists",
        ),
    ]
