# Generated by Django 5.2.5 on 2025-09-01 20:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_cmsalbum_cmssong_musicindexpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 2), ("carousel", 10), ("sql_carousel", 21), ("html", 22)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol", "max_length": 120},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Text curt baix del títol",
                            "label": "Subtítol",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol de secció", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("albums", "Àlbums"),
                                ("songs", "Cançons"),
                                ("artists", "Artistes"),
                            ],
                            "help_text": "Origen de dades del carrusel",
                            "label": "Font",
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Clau d'ordenació permesa (veure ajuda)",
                            "label": "Ordenació",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "label": "Número d’elements",
                            "max_value": 100,
                            "min_value": 1,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Per a Àlbums o Cançons",
                            "label": "Filtra per Artist ID (Spotify)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Per a Cançons",
                            "label": "Filtra per Album ID (Spotify)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "—"),
                                ("artist_names", "Noms d’artista(s)"),
                                ("popularity", "Popularitat (només cançons)"),
                                ("followers", "Followers (només artistes)"),
                            ],
                            "label": "Subtítol a mostrar",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 3),
                                ("source", 4),
                                ("order", 5),
                                ("limit", 6),
                                ("artist_id", 7),
                                ("album_id", 8),
                                ("subtitle_kind", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.SQLTable",),
                        {"label": "Taula (Snippet)"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex: id / id_spotify",
                            "label": "Camp ID (Spotify)",
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex: cover_url / imatge_url",
                            "label": "Camp imatge (URL)",
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex: album_name / nom",
                            "label": "Camp títol",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Camp subtítol (opcional)", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Si es deixa buit, no s'aplica ORDER BY",
                            "label": "Camp d’ordenació",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("ASC", "Ascendent"), ("DESC", "Descendent")],
                            "label": "Direcció",
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Camp filtre (opcional)", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "S'aplica com a = %s",
                            "label": "Valor filtre (opcional)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "label": "Filtre visible al client (no re-carrega)",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 3),
                                ("table", 11),
                                ("id_field", 12),
                                ("image_field", 13),
                                ("title_field", 14),
                                ("subtitle_field", 15),
                                ("order_field", 16),
                                ("order_direction", 17),
                                ("limit", 6),
                                ("filter_field", 18),
                                ("filter_value", 19),
                                ("filter_visible", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
    ]
