# Generated by Django 5.2.5 on 2025-09-01 20:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 2), ("carousel", 10), ("html", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol", "max_length": 120},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Text curt baix del títol",
                            "label": "Subtítol",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol de secció", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("albums", "Àlbums"),
                                ("songs", "Cançons"),
                                ("artists", "Artistes"),
                            ],
                            "help_text": "Origen de dades del carrusel",
                            "label": "Font",
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Clau d'ordenació permesa (veure ajuda)",
                            "label": "Ordenació",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "label": "Número d’elements",
                            "max_value": 100,
                            "min_value": 1,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Per a Àlbums o Cançons",
                            "label": "Filtra per Artist ID (Spotify)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Per a Cançons",
                            "label": "Filtra per Album ID (Spotify)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "—"),
                                ("artist_names", "Noms d’artista(s)"),
                                ("popularity", "Popularitat (només cançons)"),
                                ("followers", "Followers (només artistes)"),
                            ],
                            "label": "Subtítol a mostrar",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 3),
                                ("source", 4),
                                ("order", 5),
                                ("limit", 6),
                                ("artist_id", 7),
                                ("album_id", 8),
                                ("subtitle_kind", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
    ]
