# Generated by Django 5.2.5 on 2025-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="on_brand",
            field=models.CharField(
                blank=True,
                help_text="Color del text damunt del brand, ex: #FFFFFF",
                max_length=7,
            ),
        ),
    ]
