# Generated by Django 5.1.11 on 2025-09-10 19:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_scrub_legacy_sqlcarousel_and_drop_sqltable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingartist",
            name="manage_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendent"),
                    ("approved", "Aprovat"),
                    ("denied", "Denegat"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pendingartist",
            name="wants_management",
            field=models.BooleanField(
                default=False, help_text="L’usuari vol gestionar aquest artista?"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("carousel", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Títol de secció", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("albums", "Àlbums"),
                                ("songs", "Cançons"),
                                ("artists", "Artistes"),
                            ],
                            "label": "Font",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Clau d'ordenació permesa (p.ex. release_desc / release_asc).",
                            "label": "Ordenació",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "label": "Número d’elements",
                            "max_value": 100,
                            "min_value": 1,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Per a Àlbums o Cançons",
                            "label": "Filtra per Artist ID (Spotify)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Només Cançons",
                            "label": "Filtra per Album ID (Spotify)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "—"),
                                ("artist_names", "Noms d’artista(s)"),
                                ("popularity", "Popularitat (només cançons)"),
                                ("followers", "Followers (només artistes)"),
                            ],
                            "label": "Subtítol a mostrar",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 1),
                                ("source", 2),
                                ("order", 3),
                                ("limit", 4),
                                ("artist_id", 5),
                                ("album_id", 6),
                                ("subtitle_kind", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
