# Generated by Django 5.1.11 on 2025-09-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_pendingartist_manage_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrepage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="RegistreFormField",
        ),
        migrations.DeleteModel(
            name="RegistrePage",
        ),
    ]
