# Generated by Django 5.1.11 on 2025-09-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_remove_registrepage_page_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoleRequest",
        ),
    ]
