# Generated by Django 5.1.11 on 2025-09-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_delete_rolerequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserArtistPermission",
        ),
    ]
