# Generated by Django 5.1.11 on 2025-09-17 21:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_delete_userartistpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingartist",
            name="id_spotify",
            field=models.CharField(
                db_index=True,
                help_text="Només l’ID (22 caràcters). No poses l’URL.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{22}$",
                        message="id_spotify ha de tindre 22 caràcters base62",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pendingartist",
            name="manage_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendent"),
                    ("approved", "Aprovat"),
                    ("denied", "Denegat"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="pendingartist",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendent"),
                    ("approved", "Aprovat"),
                    ("denied", "Denegat"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="pendingartist",
            index=models.Index(
                fields=["status", "created_at"], name="ix_pa_stat_created"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingartist",
            index=models.Index(fields=["user", "status"], name="ix_pa_user_stat"),
        ),
        migrations.AddConstraint(
            model_name="pendingartist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("id_spotify",),
                name="uq_pa_pending_spotify",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingartist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wants_management", True),
                    ("manage_status", "pending"),
                    _connector="OR",
                ),
                name="ck_pa_manage",
            ),
        ),
    ]
