# Generated by Django 5.1.11 on 2025-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_alter_pendingartist_id_spotify_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteBranding",
            new_name="SiteDesign",
        ),
        migrations.AlterModelOptions(
            name="sitedesign",
            options={"verbose_name": "Disseny del web"},
        ),
    ]
