# Generated by Django 5.1.11 on 2025-09-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_rename_sitebranding_to_sitedesign"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedesign",
            name="base_font_size_px",
            field=models.PositiveIntegerField(
                default=16, help_text="Cos de text base (px)."
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="container_gutter",
            field=models.PositiveIntegerField(
                default=16, help_text="Marge horitzontal intern (px) del contenidor."
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="container_max_width",
            field=models.PositiveIntegerField(
                default=1180,
                help_text="Amplària màxima del contenidor (px) per a header, cos i footer.",
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Icona del lloc (es recomana PNG quadrat ≥ 180×180).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("system", "System UI (segur)"),
                    ("inter", "Inter"),
                    ("roboto", "Roboto"),
                    ("merriweather", "Merriweather (serif)"),
                ],
                default="system",
                help_text="Família tipogràfica principal.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="logo_height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Alçària màxima del logo (px). Deixa en blanc per defecte segur.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="logo_mode",
            field=models.CharField(
                choices=[
                    ("fill", "Retalla per encaixar (fill)"),
                    ("max", "Conté sense retallar (max)"),
                    ("width", "Escala per ample (width)"),
                    ("original", "Original (sense rendició)"),
                ],
                default="max",
                help_text="Com s’ajusta el logo al header.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="logo_width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amplària màxima del logo (px). Deixa en blanc per defecte segur.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="scale_ratio",
            field=models.FloatField(
                default=1.25,
                help_text="Relació d’escala per a títols (H1–H6) a partir del cos base.",
            ),
        ),
    ]
