# Generated by Django 5.1.11 on 2025-09-19 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_sitedesign_base_font_size_px_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedesign",
            name="base_font_size_px",
            field=models.PositiveIntegerField(
                default=16,
                help_text="Cos de text base (px, 14–20).",
                validators=[
                    django.core.validators.MinValueValidator(14),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="container_gutter",
            field=models.PositiveIntegerField(
                default=16,
                help_text="Marge horitzontal intern (px, 8–40) del contenidor.",
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="container_max_width",
            field=models.PositiveIntegerField(
                default=1180,
                help_text="Amplària màxima del contenidor (px, 960–1600) per a header, cos i footer.",
                validators=[
                    django.core.validators.MinValueValidator(960),
                    django.core.validators.MaxValueValidator(1600),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="header_height",
            field=models.PositiveIntegerField(
                default=96,
                help_text="Alçària header en px (56–160)",
                validators=[
                    django.core.validators.MinValueValidator(56),
                    django.core.validators.MaxValueValidator(160),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="logo_height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Alçària màxima del logo (px, 24–200). Deixa en blanc per defecte segur.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(24),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="logo_width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amplària màxima del logo (px, 24–600). Deixa en blanc per defecte segur.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(24),
                    django.core.validators.MaxValueValidator(600),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="scale_ratio",
            field=models.FloatField(
                default=1.25,
                help_text="Relació d’escala H1–H6 a partir del cos base (1.1–1.5).",
                validators=[
                    django.core.validators.MinValueValidator(1.1),
                    django.core.validators.MaxValueValidator(1.5),
                ],
            ),
        ),
    ]
