# Generated by Django 5.1.11 on 2025-09-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_sitedesign_base_font_size_px_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitedesign",
            name="link",
        ),
        migrations.RemoveField(
            model_name="sitedesign",
            name="on_brand",
        ),
    ]
