# Generated by Django 5.1.11 on 2025-09-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_remove_sitedesign_link_remove_sitedesign_on_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitedesign",
            name="footer_bg",
        ),
        migrations.RemoveField(
            model_name="sitedesign",
            name="footer_text",
        ),
        migrations.RemoveField(
            model_name="sitedesign",
            name="header_bg",
        ),
        migrations.RemoveField(
            model_name="sitedesign",
            name="header_text",
        ),
        migrations.RemoveField(
            model_name="sitedesign",
            name="logo_mode",
        ),
    ]
