# Generated by Django 5.1.11 on 2025-10-20 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_cms_artista_add_expired_field"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsartista",
            name="dones",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0%", "0%"),
                    ("<50%", "<50%"),
                    (">50%", ">50%"),
                    ("100%", "100%"),
                ],
                max_length=4,
                null=True,
                verbose_name="Dones",
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiry date/time"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="expired",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="expired"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="first published at"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="go_live_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="go live date/time"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="has_unpublished_changes",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="has unpublished changes"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="last published at"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="live",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="live"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.DeleteModel(
            name="PendingArtist",
        ),
    ]
