# Generated by Django 5.1.11 on 2025-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_cms_artista_add_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Municipi",
                    models.CharField(db_column="Municipi", max_length=50, null=True),
                ),
                (
                    "Comarca",
                    models.CharField(db_column="Comarca", max_length=50, null=True),
                ),
                (
                    "Territori",
                    models.CharField(db_column="Territori", max_length=50, null=True),
                ),
                ("Codi", models.CharField(db_column="Codi", max_length=50, null=True)),
            ],
            options={
                "db_table": "municipis",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="dones",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0%", "0%"),
                    ("<50%", "<50%"),
                    (">50%", ">50%"),
                    ("100%", "100%"),
                ],
                help_text="Percentatge de dones.",
                max_length=4,
                null=True,
                verbose_name="Dones",
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="followers",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Followers"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="id_spotify",
            field=models.CharField(
                help_text="Introdueix només l’ID (22 caràcters) — l'última part de la URL d'Spotify.",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="ID Spotify",
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="imatge_url",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Imatge (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="nom_spotify",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Nom Spotify"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="popularitat",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Popularitat"
            ),
        ),
    ]
