# Generated by Django 5.1.11 on 2025-10-21 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_municipi_alter_cmsartista_dones_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsartista",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Opcional", null=True, verbose_name="Bio"
            ),
        ),
        migrations.AlterField(
            model_name="cmsartista",
            name="id_spotify",
            field=models.CharField(
                help_text="Introdueix només l’ID. https://open.spotify.com/artist/AQUEST_ÉS_L'ID ",
                max_length=50,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_spotify_id",
                        message="Només l’ID de Spotify (22 caràcters alfanumèrics, sense URL).",
                        regex="^[A-Za-z0-9]{22}$",
                    )
                ],
                verbose_name="ID Spotify",
            ),
        ),
    ]
