# Generated by Django 5.1.11 on 2025-11-12 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0042_alter_cmsartista_bio_alter_cmsartista_id_spotify"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingSetmanal",
            fields=[
                ("data", models.DateField()),
                ("territori", models.CharField(max_length=20)),
                ("posicio", models.IntegerField(primary_key=True, serialize=False)),
                ("id_canco", models.CharField(max_length=50)),
                ("titol", models.TextField(blank=True, null=True)),
                (
                    "artistes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("album_titol", models.TextField(blank=True, null=True)),
                ("score_setmanal", models.IntegerField(blank=True, null=True)),
                (
                    "artistes_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("album_id", models.CharField(blank=True, max_length=50, null=True)),
                ("album_data", models.DateField(blank=True, null=True)),
                ("album_caratula_url", models.TextField(blank=True, null=True)),
                ("canvi_posicio", models.IntegerField(blank=True, null=True)),
                (
                    "score_global",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Rànquing setmanal (fixat)",
                "verbose_name_plural": "Rànquing setmanal (fixat)",
                "db_table": "ranking_setmanal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="RankingsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
