# Generated by Django 5.2 on 2026-04-15 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('music', '0018_add_artista_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificat', models.BooleanField(default=False)),
                ('sollicitud_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artista')),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculació usuari-artista',
                'verbose_name_plural': 'Vinculacions usuari-artista',
            },
        ),
    ]
