# Generated by Django 5.2 on 2026-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0005_lastfm_drift_detection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propostaartista",
            name="localitzacions_json",
        ),
        migrations.AddField(
            model_name="propostaartista",
            name="localitzacions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="propostaartista",
            name="deezer_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
