# Generated by Django 5.2 on 2026-04-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0006_d3_d4_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("artista", "Artista"),
                            ("album", "Àlbum"),
                            ("canco", "Cançó"),
                            ("altres", "Altres"),
                        ],
                        default="altres",
                        max_length=10,
                    ),
                ),
                ("target_pk", models.BigIntegerField(blank=True, null=True)),
                ("target_slug", models.CharField(blank=True, max_length=550)),
                ("target_label", models.CharField(blank=True, max_length=500)),
                ("missatge", models.TextField()),
                ("resolt", models.BooleanField(default=False)),
                ("notes_staff", models.TextField(blank=True)),
                ("resolt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolt_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks_resolts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback d'usuari",
                "verbose_name_plural": "Feedback d'usuaris",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resolt", "-created_at"],
                        name="comptes_fee_resolt_4e12af_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_pk"],
                        name="comptes_fee_target__bfc74b_idx",
                    ),
                ],
            },
        ),
    ]
