# Generated by Django 5.2 on 2026-04-21 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0007_feedback"),
        ("music", "0046_spotifyauth_spotifyplaylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_public", models.CharField(blank=True, max_length=120)),
                (
                    "imatge_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                (
                    "spotify_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "viasona_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "web_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "bandcamp_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "viquipedia_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "soundcloud_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "rol_musical",
                    models.CharField(
                        choices=[
                            ("escoltador", "Escoltador"),
                            ("music", "Músic"),
                            ("productor", "Productor"),
                            ("altre", "Altre"),
                        ],
                        default="escoltador",
                        max_length=20,
                    ),
                ),
                ("instruments", models.CharField(blank=True, max_length=255)),
                (
                    "visible_directori",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("obert_colaboracions", models.BooleanField(default=False)),
                ("onboarding_complet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "localitat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfil_usuaris",
                        to="music.municipi",
                    ),
                ),
                (
                    "usuari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil d'usuari",
                "verbose_name_plural": "Perfils d'usuari",
            },
        ),
        migrations.CreateModel(
            name="Publicacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titol", models.CharField(max_length=200)),
                ("cos", models.TextField(max_length=20000)),
                (
                    "visibilitat",
                    models.CharField(
                        choices=[
                            ("interna", "Interna (només usuaris registrats)"),
                            ("publica", "Pública (tothom)"),
                        ],
                        default="interna",
                        max_length=20,
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("esborrany", "Esborrany"),
                            ("pendent", "Pendent d'aprovació"),
                            ("publicat", "Publicada"),
                            ("rebutjat", "Rebutjada"),
                        ],
                        db_index=True,
                        default="esborrany",
                        max_length=20,
                    ),
                ),
                ("notes_staff", models.TextField(blank=True)),
                ("publicat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicacions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicació",
                "verbose_name_plural": "Publicacions",
                "ordering": ["-publicat_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["estat", "-created_at"],
                        name="comptes_pub_estat_3aab5d_idx",
                    ),
                    models.Index(
                        fields=["visibilitat", "estat", "-publicat_at"],
                        name="comptes_pub_visibil_bf6f19_idx",
                    ),
                ],
            },
        ),
    ]
