# Generated by Django 5.2 on 2026-04-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0008_perfilusuari_publicacio"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuari",
            name="notificar_comentaris_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="notificar_missatges_email",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Comentari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cos", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comentaris",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publicacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentaris",
                        to="comptes.publicacio",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Missatge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assumpte", models.CharField(blank=True, max_length=200)),
                ("cos", models.TextField(max_length=10000)),
                (
                    "llegit_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "destinatari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missatges_rebuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remitent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missatges_enviats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destinatari", "-created_at"],
                        name="comptes_mis_destina_919c2d_idx",
                    ),
                    models.Index(
                        fields=["remitent", "-created_at"],
                        name="comptes_mis_remiten_985be6_idx",
                    ),
                ],
            },
        ),
    ]
