# Generated by Django 5.2 on 2026-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0010_rename_auth_user_m2m_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuari",
            name="rol_musical",
            field=models.CharField(
                choices=[
                    ("escoltador", "Oïdor/a"),
                    ("music", "Músic/a"),
                    ("productor", "Productor/a"),
                    ("altre", "Altre"),
                ],
                default="escoltador",
                max_length=20,
            ),
        ),
    ]
