# Generated by Django 5.2 on 2026-04-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0017_add_ml_fields_to_historialrevisio"),
        ("ranking", "0003_senyaldiari_delete_ingestadiari_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingProvisional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("territori", models.CharField(max_length=4)),
                ("posicio", models.PositiveSmallIntegerField()),
                ("score_setmanal", models.FloatField()),
                ("lastfm_playcount", models.IntegerField(null=True)),
                ("dies_en_top", models.IntegerField(null=True)),
                ("data_calcul", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["territori", "posicio"],
            },
        ),
        migrations.RenameIndex(
            model_name="senyaldiari",
            new_name="ranking_sen_canco_i_23a029_idx",
            old_name="ranking_ing_canco_i_587ef5_idx",
        ),
        migrations.RenameIndex(
            model_name="senyaldiari",
            new_name="ranking_sen_data_cb5876_idx",
            old_name="ranking_ing_data_83e5bf_idx",
        ),
        migrations.AddField(
            model_name="rankingprovisional",
            name="canco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_provisional",
                to="music.canco",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingprovisional",
            index=models.Index(
                fields=["territori", "posicio"], name="ranking_ran_territo_498143_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rankingprovisional",
            unique_together={("canco", "territori")},
        ),
    ]
