# Generated by Django 5.2 on 2026-04-16 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_add_indexes_audit'),
        ('ranking', '0004_rankingprovisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsetmanal',
            name='algorithm_version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='rankingsetmanal',
            name='artista_nom_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rankingsetmanal',
            name='canco_nom_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rankingsetmanal',
            name='config_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='coeficient_penalitzacio_top',
            field=models.DecimalField(decimal_places=3, default=0.075, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='dia_setmana_ranking',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='exponent_penalitzacio_antiguitat',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='max_factor_a',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='max_factor_b',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='max_factor_c',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='max_factor_final',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='min_cancons_ranking_propi',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_album_per_canco',
            field=models.DecimalField(decimal_places=3, default=0.25, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_artista_per_canco',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_descens',
            field=models.DecimalField(decimal_places=3, default=0.025, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_setmana_0',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_setmana_1',
            field=models.DecimalField(decimal_places=3, default=0.05, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_setmana_2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='suavitat',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rankingprovisional',
            name='canco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_provisional', to='music.canco'),
        ),
        migrations.AlterField(
            model_name='rankingsetmanal',
            name='canco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='music.canco'),
        ),
        migrations.AlterField(
            model_name='senyaldiari',
            name='canco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senyals', to='music.canco'),
        ),
    ]
