# Generated by Django 5.2 on 2026-04-16 20:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_fill_ranking_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioglobal',
            name='coeficient_penalitzacio_top',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.075'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_artista_per_canco',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.2'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_descens',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.025'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_setmana_0',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioglobal',
            name='penalitzacio_setmana_1',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.05'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
