# Generated by Django 5.2 on 2026-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0036_d6_composite_indexes"),
        ("ranking", "0008_lastfm_drift_detection"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rankingsetmanal",
            index=models.Index(
                fields=["territori", "setmana", "posicio"],
                name="ranking_ran_territo_dd327c_idx",
            ),
        ),
    ]
