# Generated by Django 5.2 on 2026-04-23 21:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def bump_coeficient_penalitzacio_top(apps, schema_editor):
    """Move the existing row from 0.075 → 0.04 to match the new default.

    Applied only if the live value is still the pre-v2.0 default 0.075;
    staff-set custom values are preserved.
    """
    ConfiguracioGlobal = apps.get_model("ranking", "ConfiguracioGlobal")
    ConfiguracioGlobal.objects.filter(
        coeficient_penalitzacio_top=Decimal("0.075")
    ).update(coeficient_penalitzacio_top=Decimal("0.04"))


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0009_d6_composite_indexes"),
    ]

    operations = [
        migrations.RunPython(
            bump_coeficient_penalitzacio_top, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="max_factor_a",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="max_factor_b",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="max_factor_c",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="max_factor_final",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="penalitzacio_descens",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="penalitzacio_setmana_0",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="penalitzacio_setmana_1",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="penalitzacio_setmana_2",
        ),
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="suavitat",
        ),
        migrations.RemoveField(
            model_name="senyaldiari",
            name="score_entrada",
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="coeficient_penalitzacio_top",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.04"),
                help_text="Penalització per setmanes anteriors al top. Per cada aparició a la posició N acumula: coeficient_base / 2^(N-1). Ex amb 0.04: pos 1 = 4%, pos 2 = 2%, pos 3 = 1%…",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="exponent_penalitzacio_antiguitat",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.5"),
                help_text="Antiguitat: penalty = min(1, (dies/365)^exponent).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="penalitzacio_album_per_canco",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.25"),
                help_text="Monopoli àlbum: per cada cançó anterior del mateix àlbum, multiplica el score per (1 - valor). 0.25 → x0.75 per cançó.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="penalitzacio_artista_per_canco",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.2"),
                help_text="Monopoli artista: per cada cançó anterior del mateix artista al rànquing, multiplica el score per (1 - valor). 0.2 → x0.8.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
